# Generated by Django 5.1 on 2024-09-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('history', 'History'), ('english', 'English'), ('art', 'Art')], default='math', max_length=50),
        ),
    ]
