# Generated by Django 5.0.6 on 2024-09-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_student_roll_student_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(choices=[('full', 'Full-Stack Web Development'), ('mobile', 'Mobile App Development'), ('data', 'Data Science'), ('big_data', 'Big Data and Hadoop'), ('ethical', 'Ethical Hacking and Peenertration Testing'), ('cyber', 'Cybersecurity Fundamentals')], default='math', max_length=50),
        ),
    ]
