# Generated by Django 5.0.6 on 2024-09-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_cost_alter_student_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Active',
        ),
        migrations.AddField(
            model_name='student',
            name='Class_type',
            field=models.CharField(choices=[('full', 'Full-Stack Web Development'), ('mobile', 'Mobile App Development'), ('data', 'Data Science'), ('big_data', 'Big Data and Hadoop'), ('ethical', 'Ethical Hacking and Peenertration Testing'), ('cyber', 'Cybersecurity Fundamentals')], default='physical', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(choices=[('full', 'Full-Stack Web Development'), ('mobile', 'Mobile App Development'), ('data', 'Data Science'), ('big_data', 'Big Data and Hadoop'), ('ethical', 'Ethical Hacking and Peenertration Testing'), ('cyber', 'Cybersecurity Fundamentals')], default='full', max_length=50),
        ),
    ]
